import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from "@/app/lib/registry";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { montserrat } from "@/app/genericComponents/fonts";

config.autoAddCss = false;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={montserrat.className}>{children}</body>
      </StyledComponentsRegistry>
    </html>
  );
}
